services:
  db:
    image: postgres:14.4
    ports:
      - 5434:5432
    volumes:
      - ./db/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hype
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: projects/backend
    ports:
      - 8080:8080
    volumes:
      - ./projects/backend:/backend
    depends_on:
      - db
    tty: true
volumes:
  pg-data:
