services:
  db:
    build:
      context: projects/backend
      dockerfile: docker/Dockerfile.db
    ports:
      - 5434:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  backend:
    build:
      context: projects/backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    env_file:
      - projects/backend/env/${ENV}.env
    volumes:
      - ./projects/backend:/backend
    depends_on:
      - db
    tty: true
volumes:
  pg-data:
