root = "." 
tmp_dir = ".air"

[build]
cmd = "go build -o ./.air/api ./cmd/api"
bin = ".air/api"
include_ext = ["go"]
exclude_dir = [".air"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = true

[misc]
clean_on_exit = true
